[package]
name = "polkadot-primitives"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.136", optional = true, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["bit-vec", "derive"] }
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["bit-vec", "derive"] }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-keystore = { git = "https://github.com/paritytech/substrate", optional = true , branch = "sandreim/dashmap" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
runtime_primitives = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
polkadot-parachain = { path = "../parachain", default-features = false }
polkadot-core-primitives = { path = "../core-primitives", default-features = false }
trie = { package = "sp-trie", git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
hex-literal = "0.3.4"
parity-util-mem = { version = "0.11.0", default-features = false, optional = true }

[features]
default = ["std"]
std = [
	"application-crypto/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"primitives/std",
	"inherents/std",
	"trie/std",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-consensus-slots/std",
	"sp-keystore",
	"sp-std/std",
	"sp-io/std",
	"sp-version/std",
	"sp-staking/std",
	"sp-arithmetic/std",
	"runtime_primitives/std",
	"serde",
	"parity-util-mem",
	"polkadot-parachain/std",
	"polkadot-core-primitives/std",
	"bitvec/std",
	"frame-system/std",
]
runtime-benchmarks = []
