[package]
name = "xcm-simulator-example"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Examples of xcm-simulator usage."
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
scale-info = { version = "2.0.0", features = ["derive"] }

frame-system = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

xcm = { path = "../../" }
xcm-simulator = { path = "../" }
xcm-executor = { path = "../../xcm-executor" }
xcm-builder = { path = "../../xcm-builder" }
pallet-xcm = { path = "../../pallet-xcm" }
polkadot-core-primitives = { path = "../../../core-primitives" }
polkadot-runtime-parachains = { path = "../../../runtime/parachains" }
polkadot-parachain = { path = "../../../parachain" }
