[package]
name = "polkadot-node-subsystem-test-helpers"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.21"
parking_lot = "0.12.0"
polkadot-node-subsystem = { path = "../subsystem" }
polkadot-node-subsystem-util = { path = "../subsystem-util" }
polkadot-primitives = { path = "../../primitives" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

[dev-dependencies]
polkadot-overseer = { path = "../overseer" }
