[package]
name = "rialto-bridge-node"
description = "Substrate node compatible with Rialto runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
futures = "0.3"
jsonrpc-core = "18.0"
kvdb = "0.11"
kvdb-rocksdb = "0.15"
lru = "0.7"
serde_json = "1.0.59"
thiserror = "1.0"

# Bridge dependencies

bp-runtime = { path = "../../../primitives/runtime" }
bp-rialto = { path = "../../../primitives/chain-rialto" }
pallet-bridge-messages = { path = "../../../modules/messages" }
rialto-runtime = { path = "../runtime" }

# Substrate Dependencies

beefy-gadget = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
beefy-gadget-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
beefy-primitives = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
node-inspect = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
pallet-mmr-primitives = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-cli = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "sandreim/dashmap" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

# Polkadot Dependencies

polkadot-node-core-pvf = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master", default-features = false, features = [ "full-node", "polkadot-native" ] }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

[features]
default = []
runtime-benchmarks = [
	"rialto-runtime/runtime-benchmarks",
]
