[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "kpp-libp2p-0.43" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kpp-libp2p-0.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "kpp-libp2p-0.43" }
polkadot-primitives = { path = "../" }
