[package]
name = "rialto-parachain-collator"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

[[bin]]
name = 'rialto-parachain-collator'

[features]
default = []
runtime-benchmarks = ['rialto-parachain-runtime/runtime-benchmarks']

[dependencies]
clap = { version = "3.1", features = ["derive"] }
derive_more = '0.99.2'
log = '0.4.14'
codec = { package = 'parity-scale-codec', version = '3.0.0' }
serde = { version = '1.0', features = ['derive'] }
hex-literal = '0.3.1'

# RPC related Dependencies
jsonrpc-core = '18.0'

# Local Dependencies
rialto-parachain-runtime = { path = '../runtime' }

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

## Substrate Client Dependencies
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-service = { git = "https://github.com/paritytech/substrate", features = ['wasmtime'] , branch = "sandreim/dashmap" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "sandreim/dashmap" }

# Cumulus dependencies
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-collator = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-cli = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-relay-chain-inprocess-interface = { git = "https://github.com/paritytech/cumulus", branch = "master" }

# Polkadot dependencies
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }
