[package]
name = "bp-rialto-parachain"
description = "Primitives of Rialto parachain runtime."
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]

# Bridge Dependencies

bp-messages = { path = "../messages", default-features = false }
bp-runtime = { path = "../runtime", default-features = false }

# Substrate Based Dependencies

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "sandreim/dashmap" }

[features]
default = ["std"]
std = [
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
